function Get-DevOpsResolvedPackageIds { param($Config,[string[]]$CloudPackageIds=@());$definition=Get-EnvironmentDefinition $Config 'devops';$requested=@($definition.packages|Where-Object {$_ -notin @('aws_cli','azure_cli')});if($CloudPackageIds){$requested+=@($CloudPackageIds)};return @(Resolve-DevSetupPackages -Config $Config -PackageIds $requested|Select-Object -Unique) }
function Select-DevOpsCloudPackages { param([switch]$Yes);if($Yes){return @()};Write-Host 'Optional cloud tools:';Write-Host '[1] AWS CLI';Write-Host '[2] Azure CLI';Write-Host '[3] Both';Write-Host '[4] Skip';switch(Read-Host 'Select'){'1'{return @('aws_cli')}'2'{return @('azure_cli')}'3'{return @('aws_cli','azure_cli')}default{return @()}} }
function Get-DockerDiagnostic { $command=Get-Command docker.exe -ErrorAction SilentlyContinue;$desktopPaths=@((Join-Path ${env:ProgramFiles} 'Docker\Docker\Docker Desktop.exe'),(Join-Path ${env:ProgramFiles(x86)} 'Docker\Docker\Docker Desktop.exe'))|Where-Object {$_ -and(Test-Path -LiteralPath $_)};$cliVersion=$null;$daemonReachable=$null;if($command){$versionResult=Invoke-DevSetupProcess $command.Source @('--version') 8;if($versionResult.Success){$cliVersion=Extract-VersionString "$($versionResult.StdOut)`n$($versionResult.StdErr)"};$daemonResult=Invoke-DevSetupProcess $command.Source @('version','--format','{{.Server.Version}}') 8;$daemonReachable=[bool]$daemonResult.Success};$installed=[bool]$command -or $desktopPaths.Count -gt 0;$status=if(-not $installed){'MISSING'}elseif(-not $command){'INSTALLED_NOT_RUNNING'}elseif($daemonReachable){'READY'}elseif($null -eq $daemonReachable){'UNKNOWN'}else{'INSTALLED_NOT_RUNNING'};[pscustomobject]@{installed=$installed;cliAvailable=[bool]$command;daemonReachable=$daemonReachable;version=$cliVersion;desktopPath=@($desktopPaths)[0];status=$status} }
function ConvertFrom-WslDistributionOutput {
 param([AllowNull()][string]$Output)
 $clean=ConvertFrom-DevSetupNativeOutput $Output;if([string]::IsNullOrWhiteSpace($clean)){return @()}
 $details=@();foreach($line in ($clean -split "`r?`n")){$value=$line.Trim();if(-not $value -or $value -match '^(NAME|Windows Subsystem)'){continue};$default=$value.StartsWith('*');if($default){$value=$value.Substring(1).Trim()};if($value -match '^(?<name>.+?)\s{2,}(?<state>Running|Stopped)\s{2,}(?<version>[12])\s*$'){$details+=[pscustomobject]@{name=$Matches.name.Trim();state=$Matches.state;version=[int]$Matches.version;default=$default}}};return @($details)
}
function Get-WslDiagnostic {
 $command=Get-Command wsl.exe -ErrorAction SilentlyContinue;if(-not $command){return [pscustomobject]@{installed=$false;commandAvailable=$false;version=$null;defaultVersion=$null;wsl2Available=$null;distributions=@();distributionDetails=@();status='MISSING'}}
 $statusResult=Invoke-DevSetupProcess $command.Source @('--status') 8;$versionResult=Invoke-DevSetupProcess $command.Source @('--version') 8;$listResult=Invoke-DevSetupProcess $command.Source @('-l','-v') 8
 $statusText=ConvertFrom-DevSetupNativeOutput "$($statusResult.StdOut)`n$($statusResult.StdErr)";$versionText=ConvertFrom-DevSetupNativeOutput "$($versionResult.StdOut)`n$($versionResult.StdErr)";$listText=ConvertFrom-DevSetupNativeOutput "$($listResult.StdOut)`n$($listResult.StdErr)";$defaultVersion=if($statusText -match '(?im)Default Version:\s*(\d+)'){$Matches[1]}else{$null};$details=@(ConvertFrom-WslDistributionOutput $listText);$distributions=@($details|ForEach-Object {"$($_.name)    $($_.state)    $($_.version)"})
 $hasV2=@($details|Where-Object version -eq 2).Count -gt 0
 # wsl2Available is tri-state:
 # true  = any distro version 2 found, OR defaultVersion explicitly '2'
 # false = ONLY when positively confirmed no WSL2: defaultVersion explicitly '1' AND no distro exists at all
 # null  = unknown (wsl installed but no positive determination possible)
 $wsl2Available=if($hasV2){$true}elseif($defaultVersion -eq '2'){$true}elseif($statusResult.Success -and $statusText -match '(?i)WSL 2 is not supported|not supported'){$false}elseif($null -ne $defaultVersion -and $defaultVersion -eq '1' -and $details.Count -eq 0){$false}else{$null}
 $state=if($hasV2){'READY'}elseif($statusResult.Success -or $versionResult.Success -or $listResult.Success){'INSTALLED_NOT_RUNNING'}else{'UNKNOWN'}
 [pscustomobject]@{installed=$true;commandAvailable=$true;version=(Extract-VersionString $versionText);defaultVersion=$defaultVersion;wsl2Available=$wsl2Available;distributions=$distributions;distributionDetails=$details;status=$state}
}
function Get-VirtualizationDiagnostic { try{$processor=Get-CimInstance Win32_Processor -ErrorAction Stop|Select-Object -First 1;if($null -eq $processor){throw 'No processor data'};$supported=if($null -eq $processor.VMMonitorModeExtensions){$null}else{[bool]$processor.VMMonitorModeExtensions};$enabled=if($null -eq $processor.VirtualizationFirmwareEnabled){$null}else{[bool]$processor.VirtualizationFirmwareEnabled};$status=if($supported -eq $false){'UNSUPPORTED'}elseif($enabled -eq $true){'READY'}elseif($enabled -eq $false){'INSTALLED_NOT_RUNNING'}else{'UNKNOWN'};[pscustomobject]@{supported=$supported;enabled=$enabled;status=$status}}catch{[pscustomobject]@{supported=$null;enabled=$null;status='UNKNOWN'}} }
function Get-DevOpsDiagnostic { [pscustomobject]@{docker=Get-DockerDiagnostic;wsl=Get-WslDiagnostic;virtualization=Get-VirtualizationDiagnostic} }
function Invoke-DevOpsEnvironment { param($Config,[switch]$DryRun,[switch]$Yes,[switch]$VerboseMode,[switch]$NoIde);Write-DevSetupHeader -Title 'DevOps Environment';$diagnostic=Get-DevOpsDiagnostic;Write-Host "Docker: $($diagnostic.docker.status)" -ForegroundColor Gray;Write-Host "WSL: $($diagnostic.wsl.status)" -ForegroundColor Gray;$cloud=Select-DevOpsCloudPackages -Yes:($Yes -or $DryRun);$packageIds=Get-DevOpsResolvedPackageIds $Config $cloud;return Invoke-EnvironmentPipeline $Config 'devops' -PackageIds $packageIds -DryRun:$DryRun -Yes:$Yes -NoIde:$NoIde }
