$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent;$failed=@();function Test-RcGate { param([string]$Name,[scriptblock]$Action) try{& $Action;Write-Host "[PASS] $Name"}catch{$script:failed+=$Name;Write-Host "[FAIL] ${Name}: $($_.Exception.Message)" -ForegroundColor Red}}
Test-RcGate 'PowerShell parse' { $errs=@();Get-ChildItem $root -Recurse -Filter *.ps1|? FullName -notmatch '\\.git\\'|%{$t=$null;$e=$null;[void][System.Management.Automation.Language.Parser]::ParseFile($_.FullName,[ref]$t,[ref]$e);$errs+=$e};if($errs){throw ($errs.Message -join '; ')}}
Test-RcGate 'Pester' { & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'tests\run-tests.ps1');if($LASTEXITCODE -ne 0){throw 'Pester invocation failed'}}
Test-RcGate 'Doctor JSON stdout' { $capture=Join-Path $env:TEMP ('devsetup-doctor-'+([guid]::NewGuid().ToString())+'.json');& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'devsetup.ps1') doctor -Json > $capture;if($LASTEXITCODE -notin @(0,1,2)){throw 'Unexpected doctor exit code'};$raw=Get-Content $capture -Raw;$null=$raw|ConvertFrom-Json;Remove-Item $capture -Force }
Test-RcGate 'Version consistency' { $v=(Get-Content (Join-Path $root 'config\defaults.json') -Raw|ConvertFrom-Json).appVersion;if($v -ne '0.9.0-rc.1'){throw "Unexpected version $v"};$out=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'devsetup.ps1') version;if(($out -join "`n") -notmatch '0\.9\.0-rc\.1'){throw 'CLI version mismatch'}}
Test-RcGate 'Source safety' { $runtime=Get-ChildItem (Join-Path $root 'src'),(Join-Path $root 'bootstrap.ps1') -Recurse -File -ErrorAction SilentlyContinue|? Extension -eq '.ps1';$bad=$runtime|Select-String -Pattern 'Invoke-Expression|\biex\b|ExecutionPolicy\s+Bypass' -CaseSensitive:$false;if($bad){throw ($bad|% Line|Out-String)}}
Test-RcGate 'Build artifact' { & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'scripts\build-release.ps1');if($LASTEXITCODE -ne 0){throw 'Build failed'}}
Test-RcGate 'Checksum' { & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'scripts\verify-release.ps1');if($LASTEXITCODE -ne 0){throw 'Checksum failed'}}
Test-RcGate 'Archive allow-list' { $v='0.9.0-rc.1';$zip=Join-Path $root "dist\DevSetup-v$v.zip";Add-Type -AssemblyName System.IO.Compression.FileSystem;$a=[IO.Compression.ZipFile]::OpenRead($zip);try{$names=@($a.Entries|% { $_.FullName -replace '\\','/' });foreach($required in @('devsetup.ps1','src/main.ps1','config/defaults.json','config/environments.json')){if($names -notcontains $required){throw "Missing $required"}};if($names|?{$_ -match '^(tests|dist|\.git)/|\.log$|doctor-output\.json'}){throw 'Disallowed archive content'}}finally{$a.Dispose()}}
if($failed.Count){Write-Host 'RC verification FAILED' -ForegroundColor Red;exit 1};Write-Host 'RC verification PASS' -ForegroundColor Green;exit 0
